services:
  database:
    image: postgres
    container_name: exercicios-devweb-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - exercicios-devweb:/var/lib/postgresql/data
    networks:
      - exercicios-devweb

  tomcat:
    image: tomcat:latest
    container_name: exercicios-devweb-tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/webapp:/usr/local/tomcat/webapps/ROOT
    env_file:
      - .env
    working_dir: /app
    depends_on:
      - database
    networks:
      - exercicios-devweb

volumes:
  exercicios-devweb:

networks:
  exercicios-devweb: